//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/GameFolders/Scripts/Abstracts/InputSystem/DefaultActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace PanteonDemoProject.Abstracts.Inputs
{
    public partial class @DefaultActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @DefaultActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7017a8f3-5a2f-4ac8-98dc-c3c6f2725d6f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b0159a67-6db1-4951-92fd-f6157b8423bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swerve"",
                    ""type"": ""Value"",
                    ""id"": ""3c30b76f-87f1-4dbd-bb32-e7cf148b1361"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-1,max=1)"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33badbfe-fb3f-4fc1-bf07-ee9e38b59f89"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d863981-4032-4d98-962a-a00dfad51db5"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""dccb9119-6a28-4334-afc5-113447aa2cae"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""016a6e8c-eb83-47f7-a81c-8d3f692e65a8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fd71cf01-d7f8-4a6f-9667-26622992aa55"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""9b137261-9711-487b-b979-7f9465043ae8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0ec77630-26b0-494c-b5e8-31d104f367e2"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5da47976-e561-47d2-b845-51e54b5e8207"",
                    ""path"": ""<Touchscreen>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swerve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""MousePosition"",
            ""id"": ""7ba1a485-de92-4f5c-bc46-bf3fa7c376d3"",
            ""actions"": [
                {
                    ""name"": ""GetMousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""bb9611a6-0644-4e0b-aff3-954fc958bc1c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""56317c94-2eff-4183-a277-94a139baa253"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetMousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d67bd29a-c00a-4a63-8da2-75f9a9c5a0ca"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetMousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_Swerve = m_Player.FindAction("Swerve", throwIfNotFound: true);
            // MousePosition
            m_MousePosition = asset.FindActionMap("MousePosition", throwIfNotFound: true);
            m_MousePosition_GetMousePosition = m_MousePosition.FindAction("GetMousePosition", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_Swerve;
        public struct PlayerActions
        {
            private @DefaultActions m_Wrapper;
            public PlayerActions(@DefaultActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @Swerve => m_Wrapper.m_Player_Swerve;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                    @Swerve.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwerve;
                    @Swerve.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwerve;
                    @Swerve.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwerve;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Swerve.started += instance.OnSwerve;
                    @Swerve.performed += instance.OnSwerve;
                    @Swerve.canceled += instance.OnSwerve;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // MousePosition
        private readonly InputActionMap m_MousePosition;
        private IMousePositionActions m_MousePositionActionsCallbackInterface;
        private readonly InputAction m_MousePosition_GetMousePosition;
        public struct MousePositionActions
        {
            private @DefaultActions m_Wrapper;
            public MousePositionActions(@DefaultActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @GetMousePosition => m_Wrapper.m_MousePosition_GetMousePosition;
            public InputActionMap Get() { return m_Wrapper.m_MousePosition; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MousePositionActions set) { return set.Get(); }
            public void SetCallbacks(IMousePositionActions instance)
            {
                if (m_Wrapper.m_MousePositionActionsCallbackInterface != null)
                {
                    @GetMousePosition.started -= m_Wrapper.m_MousePositionActionsCallbackInterface.OnGetMousePosition;
                    @GetMousePosition.performed -= m_Wrapper.m_MousePositionActionsCallbackInterface.OnGetMousePosition;
                    @GetMousePosition.canceled -= m_Wrapper.m_MousePositionActionsCallbackInterface.OnGetMousePosition;
                }
                m_Wrapper.m_MousePositionActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @GetMousePosition.started += instance.OnGetMousePosition;
                    @GetMousePosition.performed += instance.OnGetMousePosition;
                    @GetMousePosition.canceled += instance.OnGetMousePosition;
                }
            }
        }
        public MousePositionActions @MousePosition => new MousePositionActions(this);
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnSwerve(InputAction.CallbackContext context);
        }
        public interface IMousePositionActions
        {
            void OnGetMousePosition(InputAction.CallbackContext context);
        }
    }
}
